### ISSUE TITLE
Route after login page to WinnerPage

### ISSUE THREAD

**Issue by clecardona** [clecardona/SDA-group-project#2]
- after login, user should be redirected to WinnerPage.jsx

**Comment by saramaher1** [comment]
Hello Guys, I was working on that bug I found a solution,it works when you login it goes to the WinnerPage  but the problem now is the when its go to winnerPage the path for the winner page does not show on .
does this gonna affect when we are getting data from database ?

**Comment by sangeetha-murugesan-sda9** [comment]
Hi Sara,I think this will not affect database now.We are not doing anything related to navigation in DataBase.we are done with Home Page for uploading image in DB and working on adding likes to it..
